### ISSUE TITLE
add .gitignore to the repository

### ISSUE THREAD

**Issue by amano-takahisa** [mantlelabs/Bov_validation#2]
@VighneshwarDS 
This repository doesn't have `.gitignore`, and some unsuitable files are committed, such as `db.sqlite3`, `__pycache__`.

To avoid accidentally committing an unintended file, I recommend to:

1. add `.gitignore`
2. usually commit with `git commit -u` option instead of `git commit .`
3. set `git config --global commit.verbose true` to show what you are going to commit in commit message editor
4. check what changes are included in pull requests.

A template of `.gitignore` for python code is available [here](https://github.com/github/gitignore/blob/main/Python.gitignore).

**Comment by VighneshwarDS** [comment]
Thank you for pointing it out, it was in the pending task before I went on leave. Now I have updated it.
